#!/bin/bash

now=`date '+%Y%m%d%H%M%S'`;
filepath="./dev/bin/kernel-$now.elf"

rm -rf ./dev/obj
mkdir -p ./dev/obj

rm -rf ./dev/bin
mkdir -p ./dev/bin

nasm -g -f elf32 -o ./dev/obj/kernel.o ./dev/src/kernel.asm
ld -m elf_i386 -T ./dev/src/linker.ld -o $filepath ./dev/obj/kernel.o

genisoimage -o ./dev/bin/kernel.iso $filepath

sudo qemu-system-i386 -boot c --kernel $filepath -enable-kvm